---
layout: cv
title: Isaac Newtons's CV
---
### Specialized in

Python development, Pandas, MySQL


### Research interests

Machine Learning, Deep Learning, Chat bots.


## Education

'September 2023 - now'
__Brigham Young University Idaho, Rexburg__


## Work Expereince
<p>
Subsurface Utility Engineer | CobbFendley & Associates | Sandy, Utah April 2021 - July 2021
CobbFendley & Associates is a Civil Engineering company that specializes in the classification and organization of 
subsurface utilities to facilitate and expedite the construction process
<br>
Preformed four levels of classification for a variety subsurface utilities and accurately recorded information via 
satellite survey technology and verbal communication for development in future designs
<br>
Operated efficiently in small groups of two to three people to guarantee all work was completed on time in a 
secure manner
</p>
<p>
Shift Lead | Moochie's Meatballs and More | Lehi, Utah June 2018 - December 2020
Moochie's Meatballs and More is a quick serve restaurant that specializes in serving philly food to their customers in a 
quick and delicious manner.
<br>
Guided a team of six members to accurately and promptly serve customers and encouraged all to preform to best 
potential and honed communication and coaching skills by working together as a team to maintain customer 
satisfaction
<br>
Ensured closing procedures were executed swiftly and thoroughly and safety measures were taken to protecting 
thousands of dollars of company assests
</p>

## Extra Curricular Activities

<p>
Lead a team of four in a Brigham Young University Idaho sponsored Hackathon to create a software program 
using the C+ language capable of teaching users morse code and provide an opportunity to practice AM radio 
competencies
</p>
<p>
Communicated in a campus society to study about applications and uses of Data Science and opportunity to 
instruct new university students and working as a team to work on projects
</p>
<p>
Conceptualized personal community service project to aide in child development by creating busy boards over 
three months and lead 30+ volunteers to its completion
</p>


<!-- ### Footer

Last updated: May 2013 -->


